# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Becker Rantin about Rust
email: rust@deathbyescalator.com
description: > # this means to ignore newlines until "baseurl:"
  Learning rust with borrowed time.
baseurl: "/rantin-about-rust" # the subpath of your site, e.g. /blog
url: "http://sbeckeriv.github.io" # the base hostname & protocol for your site
twitter_username: sbeckeriv
github_username:  sbeckeriv

  # Build settings
markdown: kramdown
